### ISSUE TITLE
Testing fails on some users due to timezone

### ISSUE THREAD

**Issue by htietze** [htietze/lmnop#24]
/Capstone/lmnop/lmn/tests/test_views.py", line 371, in test_add_note_database_updated_correctly
    self.assertEqual(now.date(), posted_date.date())  # TODO check time too
AssertionError: datetime.date(2020, 11, 24) != datetime.date(2020, 11, 25)

/Capstone/lmnop/lmn/tests/test_views.py", line 257, in test_artists_played_at_venue_most_recent_first
    self.assertEqual(0, (show1.show_date - expected_date).total_seconds())
AssertionError: 0 != 21600.0

2 users on MacOS Catalina

Timezone on the computer is set to Central - Chicago US, settings.py shows central as the timezone as well. Tests/terminal assume Greenwich time, 6 hour difference.

**Comment by htietze** [comment]
@claraj trying this..

**Comment by htietze** [comment]
We commented the timezone parts out! Didn't have time to check out

**Comment by claraj** [comment]
I'd recommend leaving them in and leave this issue open - keeping those messages there will make it harder to forget
