### ISSUE TITLE
create new readme.md file

### ISSUE THREAD

**Issue by mn4774jm** [htietze/lmnop#28]

**Comment by xm6264jz** [comment]
@mn4774jm what is the need for a new readme.md file we can update the original read me file

**Comment by mn4774jm** [comment]
I am under the impression that the readme file will need to explain the requirements to run the program (how to get the program running at 127.0.0.1:8000) which means the env variables we have will need to be posted to slack at the very end, present a how to use(with pictures) for the program, and state any known bugs. Yes, we will rewriting the original readme though.

**Comment by htietze** [comment]
Fixed #59
